// Jialin Li
// Each instance of Conversation holds the list of messages between two users
// as well as a "unique ID", which uniquely identify a conversation between two users
// UniqueID is generated by
// There should be at most one instance between any 2 users

class Conversation {
  final string UniqueID;
  List Messages;

  Conversation({
    required this.UniqueID,
    required this.Messages,
  });

  factory Conversation.fromJSON(Map<String, dynamic> json) {
    return Conversation(
      UniqueID = json["UniqueID"],
      Messages = json["Messages"],
    );
  }

  Map<String, dynamic> toJSON() => {
    "UniqueID" : UniqueID,
    "Messages" : Messages,
  };
}
